# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by python_ebuilder 0.0.1

EAPI="5"
[[ ${PV} = *9999* ]] && GIT_ECLASS="mercurial" || GIT_ECLASS=""
PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5} )

inherit ${GIT_ECLASS} distutils-r1 prefix


DESCRIPTION="Extract information from Python modules without importing"
HOMEPAGE="https://bitbucket.org/techtonik/astdump"

if [[ ${PV} != *9999* ]]; then
	SRC_URI="https://bitbucket.org/techtonik/astdump/tarball/v${PV} -> ${P}.tar.gz"
else
	EHG_REPO_URI="https://bitbucket.org/techtonik/astdump"
fi

LICENSE="Public Domain"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

RDEPEND="
"
DEPEND="${RDEPEND}
dev-python/setuptools[${PYTHON_USEDEP}]
"




#astdump-9999.ebuild
