# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by python_ebuilder 0.0.1

EAPI="5"
[[ ${PV} = *9999* ]] && GIT_ECLASS="mercurial" || GIT_ECLASS=""
PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5} )

inherit ${GIT_ECLASS} distutils-r1 prefix


DESCRIPTION="pure python download utility"
HOMEPAGE="http://bitbucket.org/techtonik/python-wget/"

if [[ ${PV} != *9999* ]]; then
	SRC_URI="http://bitbucket.org/techtonik/python-wget//tarball/v${PV} -> ${P}.tar.gz"
else
	EHG_REPO_URI="http://bitbucket.org/techtonik/python-wget/"
fi

LICENSE="Public Domain"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

RDEPEND="
"




#wget-9999.ebuild
