# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# Ebuild generated by python_ebuilder 0.0.1

EAPI="5"
[[ ${PV} = *9999* ]] && GIT_ECLASS="git-r3" || GIT_ECLASS=""
PYTHON_COMPAT=( python{2_7,3_4,3_5,3_6} )

inherit ${GIT_ECLASS} distutils-r1 prefix


DESCRIPTION="https://github.com/tastuteche/tastu-teche"
HOMEPAGE="https://github.com/tastuteche/tastu-teche"

if [[ ${PV} != *9999* ]]; then
	SRC_URI="https://github.com/tastuteche/tastu-teche/tarball/v${PV} -> ${P}.tar.gz"
else
	EGIT_REPO_URI="https://github.com/tastuteche/tastu-teche"
fi

LICENSE="LGPL-2+"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
#	sci-libs/scipy[${PYTHON_USEDEP}]
#	dev-python/six[${PYTHON_USEDEP}]
#	dev-python/smart_open[${PYTHON_USEDEP}]
RDEPEND="dev-python/numpy[${PYTHON_USEDEP}]
"
DEPEND="${RDEPEND}
dev-python/setuptools[${PYTHON_USEDEP}]
"




#tastu_teche-9999.ebuild
