# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# Ebuild generated by python_ebuilder 0.0.1

EAPI="5"
[[ ${PV} = *9999* ]] && GIT_ECLASS="git-r3" || GIT_ECLASS=""
PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5,3_6} )

inherit ${GIT_ECLASS} distutils-r1 prefix


DESCRIPTION="Alternating Directions Dual Decomposition"
HOMEPAGE="http://www.ark.cs.cmu.edu/AD3"

if [[ ${PV} != *9999* ]]; then
	SRC_URI="https://github.com/andre-martins/AD3/tarball/v${PV} -> ${P}.tar.gz"
else
	EGIT_REPO_URI="https://github.com/andre-martins/AD3"
fi

LICENSE=""
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

RDEPEND="
"




#ad3-9999.ebuild
