# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# Ebuild generated by python_ebuilder 0.0.1

EAPI="5"
[[ ${PV} = *9999* ]] && GIT_ECLASS="git-r3" || GIT_ECLASS=""
PYTHON_COMPAT=( python{2_7,3_4,3_5,3_6} )

inherit ${GIT_ECLASS} distutils-r1 prefix


DESCRIPTION="Clustering based on density with variable density clusters"
HOMEPAGE="http://github.com/scikit-learn-contrib/hdbscan"

if [[ ${PV} != *9999* ]]; then
	SRC_URI="http://github.com/scikit-learn-contrib/hdbscan/tarball/v${PV} -> ${P}.tar.gz"
else
	EGIT_REPO_URI="http://github.com/scikit-learn-contrib/hdbscan"
fi

LICENSE="BSD"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

RDEPEND="dev-python/cython[${PYTHON_USEDEP}]
	sci-libs/scikits_learn[${PYTHON_USEDEP}]"
DEPEND="${RDEPEND}
dev-python/setuptools[${PYTHON_USEDEP}]
"




#hdbscan-9999.ebuild
