# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# Ebuild generated by python_ebuilder 0.0.1

EAPI="5"
[[ ${PV} = *9999* ]] && GIT_ECLASS="git-r3" || GIT_ECLASS=""
PYTHON_COMPAT=( python{2_7,3_5} )

inherit ${GIT_ECLASS} distutils-r1 prefix


DESCRIPTION="Python framework for fast Vector Space Modelling"
HOMEPAGE="http://radimrehurek.com/gensim"

if [[ ${PV} != *9999* ]]; then
	SRC_URI="https://github.com/RaRe-Technologies/gensim/tarball/v${PV} -> ${P}.tar.gz"
else
	EGIT_REPO_URI="https://github.com/RaRe-Technologies/gensim"
fi

LICENSE="LGPL-2+"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

RDEPEND="dev-python/numpy[${PYTHON_USEDEP}]
	sci-libs/scipy[${PYTHON_USEDEP}]
	dev-python/six[${PYTHON_USEDEP}]
	dev-python/smart_open[${PYTHON_USEDEP}]"
DEPEND="${RDEPEND}
dev-python/setuptools[${PYTHON_USEDEP}]
"




#gensim-9999.ebuild
