# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by python_ebuilder 0.0.1

EAPI="5"
[[ ${PV} = *9999* ]] && GIT_ECLASS="git-r3" || GIT_ECLASS=""
PYTHON_COMPAT=( python{3_4,3_5,3_6} )

inherit ${GIT_ECLASS} distutils-r1 prefix


DESCRIPTION="pyclustring is a python data mining library"
HOMEPAGE="https://github.com/annoviko/pyclustering"

if [[ ${PV} != *9999* ]]; then
	SRC_URI="https://github.com/annoviko/pyclustering/tarball/v${PV} -> ${P}.tar.gz"
else
	EGIT_REPO_URI="https://github.com/annoviko/pyclustering"
fi

LICENSE="GNU Public License"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

RDEPEND="
"




#pyclustering-9999.ebuild
