# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by python_ebuilder 0.0.1

EAPI="5"
[[ ${PV} = *9999* ]] && GIT_ECLASS="git-r3" || GIT_ECLASS=""
PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5,3_6} )

inherit ${GIT_ECLASS} distutils-r1 prefix


DESCRIPTION="A framework to convert natural language to database queries."
HOMEPAGE="https://github.com/machinalis/quepy"

if [[ ${PV} != *9999* ]]; then
	SRC_URI="https://github.com/machinalis/quepy/tarball/v${PV} -> ${P}.tar.gz"
else
	EGIT_REPO_URI="https://github.com/machinalis/quepy"
fi

LICENSE="BSD"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

RDEPEND="dev-python/nltk[${PYTHON_USEDEP}]
	dev-python/refo[${PYTHON_USEDEP}]
	dev-python/SPARQLWrapper[${PYTHON_USEDEP}]"
DEPEND="${RDEPEND}
dev-python/setuptools[${PYTHON_USEDEP}]
"




#quepy-9999.ebuild
